name: myfuncitynew
description: A new Flutter project. MyFunCity is a project that was developed for the Subject Advanced Studio 2.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: 2.4.0
  firebase_auth: 4.2.3
  cloud_firestore: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0
  google_nav_bar: ^5.0.6


flutter:

  uses-material-design: true


  assets:
    - images/


  fonts:
    - family: LibreCaslonText
      fonts:
        - asset: fonts/libre/LibreCaslonText-Bold.ttf
        - asset: fonts/libre/LibreCaslonText-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Italic.ttf
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-Light.ttf
